/*
 * Class: CMSC203 
 * Instructor: Professor Ahmed Tarik
 * Description: (This program builds an application that will  receive a guess and report it
  				if the user guess is the random number that was generated by the computer.)
 * Due: 2/21/2021
 * Platform/compiler: Ecclipse
 * I pledge that I have completed the programming assignment independently.
   I have not copied the code from a student or any source.
   I have not given my code to any student.
   Print your Name here: Enchalew Abebe
*/

import java.util.Scanner;
import java.util.Random;
/**
 * @author Enchalew Abebe
 *
 */
public class RandomNumberGuesser {

	     static int lowGuess=1,highGuess=100;
	
 public static void main(String[] args) {
	        Scanner input = new Scanner(System.in);
	        Random RandNum = new Random();
	     
	         int correctNumber;
	         correctNumber = RandNum.nextInt(100)+ 1;
	         int guessNumber;
	         String answer;
	         int NumberOfGuess=0;
	        System.out.println(" The correct number is " + correctNumber);
	       
	         // It validate and iterate the loop if the user answer is yes
	      do {
	    	  System.out.println(" Enter your first guess:");
	    	  guessNumber = input.nextInt();
	    	  
	    	  // It validate and iterate if guess number is not equals to the correct numbers 
	    	   do {
	     
	    		   /*it validate and iterate it if the guess number is greater than or equal to high guess or if the guess
	    		   number is less than or equals to low guess */
	    		 do {
	        		NumberOfGuess++;
	        		
	        		/* it checks whether the users guess number is greater than or equals to high guess or 
	        		less or equals to low guess, and if the user's number in this range, it will display the guess must be 
	        		between the low guess and the high guess
	        		*/
	        		if (guessNumber >=highGuess || guessNumber <= lowGuess )
	        			{
	        				System.out.println(" >>>>>> Guess must be between "+lowGuess + " and " + highGuess 
    							+ ". Try again ");
	        				guessNumber = input.nextInt();
	        			}
    				
	        	// Check if the guess number is less than the correct number
	        if(guessNumber < correctNumber)
    			{
        		
    				lowGuess=guessNumber;
    				/*
    				 * It display the number of guess, the guess is too low and ask the 
    				 * user to enter a next guess between the low guess and the high guess
    				 */
    				System.out.println(" Number of guesses is : "+ NumberOfGuess );
    				System.out.println(" Your guess is too low ");
    				lowGuess= lowGuess;
    				System.out.println(" Enter your next guess between "+lowGuess +" and "+highGuess );
    				guessNumber = input.nextInt();
        				
    			}
        		
        		// Check if guessNumber is higher than correctNumber       
	        else if(guessNumber > correctNumber)
    			{
    					highGuess=guessNumber;
    					
    					/* It display the number of guess, guess is too high 
    					and ask the user to enter number between low guess and high guess
    					*/
    					System.out.println(" Number of guesses is: " + NumberOfGuess);
    					System.out.println(" Your guess is too high ");
    					highGuess=highGuess;

    					System.out.println(" Enter your next guess between "+lowGuess +" and "+highGuess );
    					guessNumber = input.nextInt();
    			}
	        	
	        	}while (guessNumber >=highGuess || guessNumber<=lowGuess);
        		
	      }while(guessNumber != correctNumber);
        		
	      /*Check if the guess number is equal to the correct number and 
	    	   display congratulation message and ask the user to try again
	    	   */
	    	    if (guessNumber == correctNumber) 
	    	   
        			System.out.println(" Congratulation, guessed correctly. ");
        			System.out.println(" Do you want try again? (yes or no)");
        			answer = input.nextLine();
        			answer = input.nextLine();
	    	   
        			
	      }while( answer.equalsIgnoreCase("yes"));
	      
	      // displaying thank you message if the user's answer is "No"
	      
	      System.out.println(" Thank you for playing...");
	     
}

}